name: Probe 4 job if control
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  probe:
    if: matrix.tag != ''
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [t_a]
    steps:
      - run: echo "RAN ${{ matrix.tag }}"
